### ISSUE TITLE
@cainiaowu 来这个repo讨论如何

### ISSUE THREAD

**Issue by GeekDuanLian** [GeekDuanLian/cdda_zh-cn#1]
@cainiaowu

看你最近一直在更改一些老旧的翻译，并且似乎和我的更改有一些冲突
与其改来改去，不如我们在这个repo协商好再改如何？

可以继续在 Transifex 上操作，这个repo已经设置好了每天自动下载po文件，可以看到每天的更改记录
如果看到更改记录有争议的，可以先提交 issue 进行讨论
po文件不会自动上传，因为这样可能会覆盖其他翻译人员的改动，最终的更改仍需要去 Transifex 上操作

我对其他的翻译人员也不熟悉，但如果你有认识的，希望也可以叫他们来这个repo一起探讨

**Comment by cainiaowu** [comment]
可以用transifex自带的消息功能，发github不常看的。
目前改动的主要是读起来太像机翻的string。

**Comment by GeekDuanLian** [comment]
> 可以用transifex自带的消息功能，发github不常看的。 目前改动的主要是读起来太像机翻的string。

transifex的私信只能一对一吧，可能有些情况需要多人讨论，或者公示讨论结果给后面的人看的
而且不是所有人都有transifex权限，有些只是单纯的玩家想反馈

比如python的文档也是这样反馈的，他们同样也是在transifex工作
https://github.com/python/python-docs-zh-cn/issues
